### Price

In [272]:
from bs4 import BeautifulSoup
import requests
import webbrowser
import pandas as pd

In [312]:
subdf = pd.read_csv('Suburb_Data_Full_v11.csv', sep=',')

In [313]:
nmefunc = lambda x: x.lower().strip()
subdf['suburb'] = subdf.suburb.dropna().apply(nmefunc)
pricedf = subdf[['suburb_id','suburb']]

In [314]:
subdf.count()

Unnamed: 0                                            327
index                                                 327
community_name                                        327
region                                                327
map_reference                                         327
grid_reference                                        327
location                                              327
population_density                                    327
travel_time_gpo                                       327
distance_to_gpo                                       327
lga                                                   327
primary_care_partnership                              327
medicare_local                                        327
area                                                  327
aria_min                                              327
aria_max                                              327
aria_avg                                              327
abs_remoteness_category                               327
dhs_area                                              327
commercial                                            327
commercial_percent                                    327
industrial                                            327
industrial_percent                                    327
residential                                           327
residential_percent                                   327
rural                                                 327
rural_percent                                         327
other                                                 327
other_percent                                         327
erp_age_0_4_2012                                      327
                                                     ...
top_language_spoken_4                                 327
top_language_spoken_persons_4                         327
top_language_spoken_pecent_4                          327
top_language_spoken_5                                 327
top_language_spoken_persons_5                         327
top_language_spoken_percent_5                         327
public_hospital_separations                           327
nearest_public_hospital                               327
travel_time_nearest_public_hospital                   327
distance_nearest_public_hospital                      327
obstetric_type_separations                            327
public_hospital_maternity_services                    327
public_hospital_maternity_services_time               327
public_hospital_maternity_services_distance           327
presentations_emergency_departments                   327
public_hospital_emergency_department                  327
public_hospital_emergency_department_time             327
public_hospital_emergency_department_distance         327
presentations_emergency_departments_injury            327
presentations_emergency_departments_injury_percent    327
emergency department presentations                    327
emergency department presentations_percent            327
postcode                                              327
suburb                                                327
state                                                 327
dc                                                    327
type                                                  327
lat                                                   327
lon                                                   327
suburb_id                                             327
dtype: int64

In [275]:
pricedf['house_low_quartile']=0
pricedf['house_median_quartile']=0
pricedf['house_high_quartile']=0
pricedf['unit_low_quartile']=0
pricedf['unit_median_quartile']=0 
pricedf['unit_high_quartile']=0

/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [276]:
# tempdf1 = pd.DataFrame().T
# i=0
temp2 = 0
temp3 = 0
for index, row in pricedf.iterrows():
# def price(suburb):
 
#     i  = index+1
    print row['suburb']
    r  = requests.get("https://propertydata.realestateview.com.au/propertydata/median-prices/victoria/"+row['suburb']+"/")
    data = r.text
    soup = BeautifulSoup(data)
    i=0
    temparray = []
    print row['suburb']
    for row1 in soup.find_all('tr'):
        i = i+1
        if i==4:
            break
        else:
            temparray.append(row1.text)
    
    new_list = [temparray[i:i+1] for i in range(0, len(temparray), 1)]

    
    try:
        temp2 = [(w.replace(',', '')).replace('\nHouse\n$', '',1).replace('\n','').replace('$',' ') for w in  new_list[1]]
        temp2 = map(int,[word for line in temp2 for word in line.split()])
    except:
        temp2 = [0,0,0]
    try:   
        temp3 = [(w.replace(',', '')).replace('\nUnit\n $', '',1).replace('\n','').replace('$','') for w in  new_list[2]]
        temp3 = map(int,[word for line in temp3 for word in line.split()])
    except:
        temp3 = [0,0,0]
    temp = [index,row['suburb']] +temp2 + temp3
    
    print temp
    pricedf.loc[index] = temp

Abbotsford
Abbotsford
[0, 'Abbotsford', 1165000, 1271000, 1490000, 399000, 557500, 810000]
Aberfeldie
Aberfeldie
[1, 'Aberfeldie', 0, 0, 0, 0, 0, 0]
Airport West
Airport West
[2, 'Airport West', 810000, 888750, 1035500, 540000, 680000, 733750]
Albanvale
Albanvale
[3, 'Albanvale', 514000, 535000, 572000, 0, 0, 0]
Albert Park
Albert Park
[4, 'Albert Park', 1605000, 2120000, 2905000, 0, 0, 0]
Alfredton
Alfredton
[5, 'Alfredton', 355000, 440000, 480000, 0, 0, 0]
Altona North
Altona North
[6, 'Altona North', 807000, 855000, 910000, 592000, 650000, 723000]
Ardeer
Ardeer
[7, 'Ardeer', 570000, 630000, 660000, 0, 0, 0]
Armadale
Armadale
[8, 'Armadale', 1705000, 2247500, 4100000, 550000, 725750, 1200000]
Ascot
Ascot
[9, 'Ascot', 0, 0, 0, 0, 0, 0]
Ascot Vale
Ascot Vale
[10, 'Ascot Vale', 1050000, 1255000, 1400000, 440000, 525000, 880000]
Ashburton
Ashburton
[11, 'Ashburton', 1702500, 1850000, 2129000, 0, 0, 0]
Ashwood
Ashwood
[12, 'Ashwood', 1212000, 1335000, 1495000, 822000, 890000, 1320000]
Aspendale Gardens
Aspendale Gardens
[13, 'Aspendale Gardens', 845000, 911000, 950000, 0, 0, 0]
Aspendale
Aspendale
[14, 'Aspendale', 1200000, 1352500, 1431000, 0, 0, 0]
Attwood
Attwood
[15, 'Attwood', 0, 0, 0, 0, 0, 0]
Avondale Heights
Avondale Heights
[16, 'Avondale Heights', 835000, 900000, 1000000, 0, 0, 0]
Avonsleigh
Avonsleigh
[17, 'Avonsleigh', 0, 0, 0, 0, 0, 0]
Bakery Hill
Bakery Hill
[18, 'Bakery Hill', 0, 0, 0, 0, 0, 0]
Balaclava
Balaclava
[19, 'Balaclava', 0, 0, 0, 535000, 576500, 667000]
Ballarat Central
Ballarat Central
[20, 'Ballarat Central', 293250, 382000, 465000, 0, 0, 0]
Ballarat East
Ballarat East
[21, 'Ballarat East', 274500, 315000, 370000, 0, 0, 0]
Ballarat North
Ballarat North
[22, 'Ballarat North', 256000, 339750, 367500, 0, 0, 0]
Balwyn
Balwyn
[23, 'Balwyn', 1810000, 2255500, 2870000, 720000, 860000, 1280000]
Bangholme
Bangholme
[24, 'Bangholme', 0, 0, 0, 0, 0, 0]
Bayswater North
Bayswater North
[25, 'Bayswater North', 683000, 730500, 785000, 440000, 522500, 617500]
Bayswater
Bayswater
[26, 'Bayswater', 708000, 800500, 900000, 435000, 485000, 600000]
Beaconsfield
Beaconsfield
[27, 'Beaconsfield', 585000, 692500, 875000, 0, 0, 0]
Beaumaris
Beaumaris
[28, 'Beaumaris', 1445000, 1690000, 1842500, 845000, 1205000, 1600000]
Belgrave Heights
Belgrave Heights
[29, 'Belgrave Heights', 0, 0, 0, 0, 0, 0]
Belgrave
Belgrave
[30, 'Belgrave', 550000, 587000, 680000, 0, 0, 0]
Bell Park
Bell Park
[31, 'Bell Park', 344000, 368000, 420000, 0, 0, 0]
Bell Post Hill
Bell Post Hill
[32, 'Bell Post Hill', 405000, 440000, 480000, 0, 0, 0]
Bellfield
Bellfield
[33, 'Bellfield', 0, 0, 0, 0, 0, 0]
Belmont
Belmont
[34, 'Belmont', 430000, 491000, 555000, 235000, 317000, 450000]
Bendigo
Bendigo
[35, 'Bendigo', 323750, 377500, 520000, 0, 0, 0]
Bentleigh East
Bentleigh East
[36, 'Bentleigh East', 1137500, 1261117, 1440000, 850000, 1069500, 1270000]
Bentleigh
Bentleigh
[37, 'Bentleigh', 1199000, 1440500, 1710000, 678000, 830000, 1257500]
Berwick
Berwick
[38, 'Berwick', 607500, 690000, 803000, 0, 0, 0]
Bittern
Bittern
[39, 'Bittern', 0, 0, 0, 0, 0, 0]
Black Rock
Black Rock
[40, 'Black Rock', 1633500, 2120000, 2960000, 0, 0, 0]
Blackburn North
Blackburn North
[41, 'Blackburn North', 1090000, 1130250, 1280000, 0, 0, 0]
Blackburn South
Blackburn South
[42, 'Blackburn South', 990000, 1261000, 1350000, 0, 0, 0]
Blackburn
Blackburn
[43, 'Blackburn', 1219500, 1430000, 1571000, 560000, 783750, 980000]
Blairgowrie
Blairgowrie
[44, 'Blairgowrie', 0, 0, 0, 0, 0, 0]
Bonbeach
Bonbeach
[45, 'Bonbeach', 765000, 855000, 880000, 580000, 614000, 755000]
Boronia
Boronia
[46, 'Boronia', 655000, 706500, 775000, 482000, 555000, 658000]
Box Hill North
Box Hill North
[47, 'Box Hill North', 1255000, 1365000, 1561000, 685000, 802500, 1000000]
Box Hill South
Box Hill South
[48, 'Box Hill South', 1337500, 1483000, 1588500, 0, 0, 0]
Braybrook
Braybrook
[49, 'Braybrook', 0, 0, 0, 471000, 500000, 580000]
Briar Hill
Briar Hill
[50, 'Briar Hill', 0, 0, 0, 0, 0, 0]
Brighton East
Brighton East
[51, 'Brighton East', 1605000, 1925000, 2400000, 910000, 1222500, 1445000]
Brighton
Brighton
[52, 'Brighton', 2018000, 2600000, 3250000, 1002500, 1370000, 1900000]
Broadmeadows
Broadmeadows
[53, 'Broadmeadows', 500000, 540000, 600000, 0, 0, 0]
Brunswick East
Brunswick East
[54, 'Brunswick East', 1105000, 1265000, 1350000, 470000, 570000, 685000]
Brunswick
Brunswick
[55, 'Brunswick', 990000, 1267500, 1495000, 441000, 541000, 729000]
Brunswick West
Brunswick West
[56, 'Brunswick West', 1086000, 1204000, 1312500, 408750, 445000, 636500]
Bundoora
Bundoora
[57, 'Bundoora', 673000, 748750, 822500, 355000, 385000, 525000]
Buninyong
Buninyong
[58, 'Buninyong', 410000, 510000, 560000, 0, 0, 0]
Burnley
Burnley
[59, 'Burnley', 0, 0, 0, 0, 0, 0]
Burnside Heights
Burnside Heights
[60, 'Burnside Heights', 481000, 550000, 599500, 0, 0, 0]
Burwood East
Burwood East
[61, 'Burwood East', 1061000, 1180000, 1403000, 0, 0, 0]
Burwood
Burwood
[62, 'Burwood', 1251000, 1385000, 1642000, 720000, 868000, 1015000]
Cairnlea
Cairnlea
[63, 'Cairnlea', 645000, 710000, 775000, 0, 0, 0]
Camberwell
Camberwell
[64, 'Camberwell', 1855000, 2108000, 2700000, 771000, 855000, 1283000]
Canterbury
Canterbury
[65, 'Canterbury', 2192500, 2550000, 3612500, 0, 0, 0]
Carlton North
Carlton North
[66, 'Carlton North', 1470000, 1717500, 2400000, 0, 0, 0]
Carlton
Carlton
[67, 'Carlton', 0, 0, 0, 320000, 570000, 926000]
Carnegie
Carnegie
[68, 'Carnegie', 1385000, 1455000, 1653500, 515000, 705000, 1086000]
Carrum Downs
Carrum Downs
[69, 'Carrum Downs', 495000, 525000, 570000, 375000, 389500, 440000]
Carrum
Carrum
[70, 'Carrum', 0, 0, 0, 450000, 555000, 620000]
Caulfield East
Caulfield East
[71, 'Caulfield East', 0, 0, 0, 0, 0, 0]
Caulfield South
Caulfield South
[72, 'Caulfield South', 1189000, 1605000, 2142500, 529000, 777500, 1100000]
Caulfield
Caulfield
[73, 'Caulfield', 0, 0, 0, 570000, 740000, 1210000]
Chadstone
Chadstone
[74, 'Chadstone', 1040500, 1168000, 1354000, 705000, 842750, 956000]
Cheltenham
Cheltenham
[75, 'Cheltenham', 1030000, 1155500, 1250000, 580000, 689000, 760000]
Chirnside Park
Chirnside Park
[76, 'Chirnside Park', 650000, 765000, 850000, 0, 0, 0]
Clayton
Clayton
[77, 'Clayton', 1106000, 1275000, 1650000, 465000, 612500, 750000]
Clematis
Clematis
[78, 'Clematis', 0, 0, 0, 0, 0, 0]
Clifton Hill
Clifton Hill
[79, 'Clifton Hill', 1015000, 1480000, 1730000, 0, 0, 0]
Coburg North
Coburg North
[80, 'Coburg North', 761000, 865000, 922000, 490000, 622500, 801000]
Cockatoo
Cockatoo
[81, 'Cockatoo', 450500, 529000, 636000, 0, 0, 0]
Coldstream
Coldstream
[82, 'Coldstream', 0, 0, 0, 0, 0, 0]
Collingwood
Collingwood
[83, 'Collingwood', 0, 0, 0, 542000, 740000, 1162500]
Corio
Corio
[84, 'Corio', 261750, 304250, 343500, 0, 0, 0]
Craigieburn
Craigieburn
[85, 'Craigieburn', 460000, 495000, 563250, 340000, 365000, 390000]
Cranbourne South
Cranbourne South
[86, 'Cranbourne South', 0, 0, 0, 0, 0, 0]
Cranbourne
Cranbourne
[87, 'Cranbourne', 431138, 472000, 546000, 0, 0, 0]
Cranbourne West
Cranbourne West
[88, 'Cranbourne West', 446000, 485000, 555000, 0, 0, 0]
Croydon North
Croydon North
[89, 'Croydon North', 774000, 841000, 916000, 425000, 521500, 658500]
Croydon
Croydon
[90, 'Croydon', 675000, 810000, 890000, 436000, 510000, 650000]
Dallas
Dallas
[91, 'Dallas', 380000, 408500, 435500, 0, 0, 0]
Dandenong North
Dandenong North
[92, 'Dandenong North', 580500, 630500, 705000, 338000, 413000, 466500]
Dandenong
Dandenong
[93, 'Dandenong', 580000, 625000, 686000, 260500, 370000, 445000]
Deer Park
Deer Park
[94, 'Deer Park', 521000, 590550, 630000, 0, 0, 0]
Delacombe
Delacombe
[95, 'Delacombe', 320000, 365000, 415000, 0, 0, 0]
Delahey
Delahey
[96, 'Delahey', 430000, 520000, 575000, 0, 0, 0]
Devon Meadows
Devon Meadows
[97, 'Devon Meadows', 0, 0, 0, 0, 0, 0]
Diamond Creek
Diamond Creek
[98, 'Diamond Creek', 640000, 726444, 906500, 0, 0, 0]
Dingley Village
Dingley Village
[99, 'Dingley Village', 802500, 891925, 980750, 0, 0, 0]
Docklands
Docklands
[100, 'Docklands', 0, 0, 0, 480000, 539000, 815000]
Doncaster East
Doncaster East
[101, 'Doncaster East', 1255000, 1441000, 1570000, 691000, 860500, 1050000]
Doncaster
Doncaster
[102, 'Doncaster', 1370000, 1500000, 1616000, 557000, 751150, 960000]
Donvale
Donvale
[103, 'Donvale', 1160000, 1305000, 1650000, 630000, 835000, 920000]
Doreen
Doreen
[104, 'Doreen', 485000, 542500, 673250, 0, 0, 0]
Doveton
Doveton
[105, 'Doveton', 450000, 465000, 498000, 0, 0, 0]
Dromana
Dromana
[106, 'Dromana', 545000, 687000, 812000, 0, 0, 0]
Drumcondra
Drumcondra
[107, 'Drumcondra', 0, 0, 0, 0, 0, 0]
Eaglehawk
Eaglehawk
[108, 'Eaglehawk', 232500, 275000, 285000, 0, 0, 0]
Eaglemont
Eaglemont
[109, 'Eaglemont', 0, 0, 0, 0, 0, 0]
East Bendigo
East Bendigo
[110, 'East Bendigo', 0, 0, 0, 0, 0, 0]
East Geelong
East Geelong
[111, 'East Geelong', 512000, 583750, 633750, 0, 0, 0]
East Melbourne
East Melbourne
[112, 'East Melbourne', 0, 0, 0, 660000, 810000, 1350000]
Edithvale
Edithvale
[113, 'Edithvale', 850000, 1130000, 1260000, 555000, 650000, 810000]
Eltham
Eltham
[114, 'Eltham', 832000, 860500, 1010000, 720000, 730000, 765000]
Elwood
Elwood
[115, 'Elwood', 1420000, 2013000, 3107500, 495000, 655000, 810000]
Emerald
Emerald
[116, 'Emerald', 610000, 755000, 835000, 0, 0, 0]
Endeavour Hills
Endeavour Hills
[117, 'Endeavour Hills', 586500, 625000, 730000, 0, 0, 0]
Epsom
Epsom
[118, 'Epsom', 0, 0, 0, 0, 0, 0]
Essendon North
Essendon North
[119, 'Essendon North', 0, 0, 0, 0, 0, 0]
Essendon
Essendon
[120, 'Essendon', 1235000, 1410000, 1730000, 408250, 551000, 789000]
Eumemmerring
Eumemmerring
[121, 'Eumemmerring', 0, 0, 0, 0, 0, 0]
Fairfield
Fairfield
[122, 'Fairfield', 0, 0, 0, 0, 0, 0]
Fawkner
Fawkner
[123, 'Fawkner', 679000, 710000, 761000, 520000, 551000, 600000]
Ferntree Gully
Ferntree Gully
[124, 'Ferntree Gully', 696000, 750000, 805000, 521000, 536250, 630000]
Ferny Creek
Ferny Creek
[125, 'Ferny Creek', 0, 0, 0, 0, 0, 0]
Flemington
Flemington
[126, 'Flemington', 0, 0, 0, 305000, 500000, 603000]
Forest Hill
Forest Hill
[127, 'Forest Hill', 955000, 1092500, 1206000, 626000, 702500, 764000]
Frankston North
Frankston North
[128, 'Frankston North', 450000, 470000, 500000, 0, 0, 0]
Frankston South
Frankston South
[129, 'Frankston South', 720000, 817500, 950000, 471000, 535000, 601000]
Gardenvale
Gardenvale
[130, 'Gardenvale', 0, 0, 0, 0, 0, 0]
Geelong
Geelong
[131, 'Geelong', 591000, 717500, 770000, 0, 0, 0]
Geelong West
Geelong West
[132, 'Geelong West', 535000, 674500, 735000, 0, 0, 0]
Glen Huntly
Glen Huntly
[133, 'Glen Huntly', 0, 0, 0, 387500, 535000, 757000]
Glen Waverley
Glen Waverley
[134, 'Glen Waverley', 1193000, 1405000, 1716000, 731931, 952000, 1125000]
Glenroy
Glenroy
[135, 'Glenroy', 690000, 793000, 852500, 480000, 551000, 622500]
Golden Gully
Golden Gully
[136, 'Golden Gully', 0, 0, 0, 0, 0, 0]
Golden Square
Golden Square
[137, 'Golden Square', 231500, 272500, 325000, 0, 0, 0]
Gowanbrae
Gowanbrae
[138, 'Gowanbrae', 0, 0, 0, 0, 0, 0]
Greensborough
Greensborough
[139, 'Greensborough', 753000, 815500, 905500, 510000, 660000, 750000]
Greenvale
Greenvale
[140, 'Greenvale', 690000, 758500, 870000, 0, 0, 0]
Grovedale
Grovedale
[141, 'Grovedale', 375000, 400000, 435000, 0, 0, 0]
Hallam
Hallam
[142, 'Hallam', 526000, 601000, 620000, 0, 0, 0]
Hamlyn Heights
Hamlyn Heights
[143, 'Hamlyn Heights', 490000, 576500, 610000, 0, 0, 0]
Hampton Park
Hampton Park
[144, 'Hampton Park', 450000, 483000, 520000, 0, 0, 0]
Harkaway
Harkaway
[145, 'Harkaway', 0, 0, 0, 0, 0, 0]
Hastings
Hastings
[146, 'Hastings', 475000, 590000, 1000000, 0, 0, 0]
Heatherton
Heatherton
[147, 'Heatherton', 0, 0, 0, 0, 0, 0]
Heathmont
Heathmont
[148, 'Heathmont', 850000, 875000, 1000000, 0, 0, 0]
Heidelberg Heights
Heidelberg Heights
[149, 'Heidelberg Heights', 682000, 783000, 900000, 0, 0, 0]
Heidelberg
Heidelberg
[150, 'Heidelberg', 0, 0, 0, 580000, 655000, 828000]
Heidelberg West
Heidelberg West
[151, 'Heidelberg West', 613000, 705000, 855000, 0, 0, 0]
Highett
Highett
[152, 'Highett', 1210000, 1400000, 1445000, 560000, 727000, 1007000]
Highton
Highton
[153, 'Highton', 515000, 610000, 739000, 0, 0, 0]
Hillside
Hillside
[154, 'Hillside', 560000, 610000, 680000, 0, 0, 0]
Hoppers Crossing
Hoppers Crossing
[155, 'Hoppers Crossing', 475000, 520000, 565000, 0, 0, 0]
Huntingdale
Huntingdale
[156, 'Huntingdale', 0, 0, 0, 0, 0, 0]
Huntly
Huntly
[157, 'Huntly', 0, 0, 0, 0, 0, 0]
Hurstbridge
Hurstbridge
[158, 'Hurstbridge', 635000, 696500, 860000, 0, 0, 0]
Ironbark
Ironbark
[159, 'Ironbark', 0, 0, 0, 0, 0, 0]
Ivanhoe East
Ivanhoe East
[160, 'Ivanhoe East', 0, 0, 0, 0, 0, 0]
Ivanhoe
Ivanhoe
[161, 'Ivanhoe', 1250000, 1413500, 1840000, 657500, 868750, 941500]
Jacana
Jacana
[162, 'Jacana', 0, 0, 0, 0, 0, 0]
Junction Village
Junction Village
[163, 'Junction Village', 0, 0, 0, 0, 0, 0]
Junortoun
Junortoun
[164, 'Junortoun', 0, 0, 0, 0, 0, 0]
Kangaroo Flat
Kangaroo Flat
[165, 'Kangaroo Flat', 225000, 240000, 325000, 0, 0, 0]
Keilor Downs
Keilor Downs
[166, 'Keilor Downs', 605000, 645250, 730000, 0, 0, 0]
Keilor East
Keilor East
[167, 'Keilor East', 783500, 860000, 935000, 635000, 712500, 828000]
Keilor Lodge
Keilor Lodge
[168, 'Keilor Lodge', 0, 0, 0, 0, 0, 0]
Keilor
Keilor
[169, 'Keilor', 700000, 895000, 1335000, 0, 0, 0]
Kensington
Kensington
[170, 'Kensington', 990000, 1145000, 1330000, 390000, 531500, 740000]
Kew East
Kew East
[171, 'Kew East', 1700000, 1975000, 2258000, 0, 0, 0]
Keysborough
Keysborough
[172, 'Keysborough', 700000, 755000, 920000, 0, 0, 0]
Kilsyth
Kilsyth
[173, 'Kilsyth', 600000, 700000, 740000, 595000, 633709, 640000]
Kings Park
Kings Park
[174, 'Kings Park', 497000, 528000, 546500, 0, 0, 0]
Kingsville
Kingsville
[175, 'Kingsville', 995000, 1149000, 1205000, 0, 0, 0]
Knoxfield
Knoxfield
[176, 'Knoxfield', 836000, 990000, 1106000, 0, 0, 0]
Kooyong
Kooyong
[177, 'Kooyong', 0, 0, 0, 0, 0, 0]
Lake Gardens
Lake Gardens
[178, 'Lake Gardens', 0, 0, 0, 0, 0, 0]
Lake Wendouree
Lake Wendouree
[179, 'Lake Wendouree', 765000, 885000, 1025000, 0, 0, 0]
Lalor
Lalor
[180, 'Lalor', 568500, 605000, 683750, 375000, 441250, 455000]
Langwarrin South
Langwarrin South
[181, 'Langwarrin South', 0, 0, 0, 0, 0, 0]
Langwarrin
Langwarrin
[182, 'Langwarrin', 535000, 606000, 700000, 410000, 425000, 514000]
Laverton North
Laverton North
[183, 'Laverton North', 0, 0, 0, 0, 0, 0]
Laverton
Laverton
[184, 'Laverton', 505000, 557500, 612000, 0, 0, 0]
Lilydale
Lilydale
[185, 'Lilydale', 635000, 735750, 910000, 400000, 441250, 495500]
Lovely Banks
Lovely Banks
[186, 'Lovely Banks', 0, 0, 0, 0, 0, 0]
Lower Plenty
Lower Plenty
[187, 'Lower Plenty', 800000, 1024000, 1535000, 0, 0, 0]
Lysterfield South
Lysterfield South
[188, 'Lysterfield South', 0, 0, 0, 0, 0, 0]
Macleod
Macleod
[189, 'Macleod', 768500, 992000, 1157500, 0, 0, 0]
Maidstone
Maidstone
[190, 'Maidstone', 585000, 793000, 873000, 502750, 675000, 760000]
Malvern East
Malvern East
[191, 'Malvern East', 1715157, 2025000, 2770000, 429000, 872500, 1380000]
Malvern
Malvern
[192, 'Malvern', 2280000, 2750000, 3420000, 455000, 592000, 961000]
Maribyrnong
Maribyrnong
[193, 'Maribyrnong', 940000, 1155000, 1620000, 395000, 490000, 580000]
Meadow Heights
Meadow Heights
[194, 'Meadow Heights', 420000, 491500, 590000, 0, 0, 0]
Melbourne Airport
Melbourne Airport
[195, 'Melbourne Airport', 0, 0, 0, 0, 0, 0]
Melbourne
Melbourne
[196, 'Melbourne', 0, 0, 0, 390000, 499000, 650000]
Menzies Creek
Menzies Creek
[197, 'Menzies Creek', 0, 0, 0, 0, 0, 0]
Mernda
Mernda
[198, 'Mernda', 470000, 521250, 596000, 0, 0, 0]
Middle Park
Middle Park
[199, 'Middle Park', 0, 0, 0, 0, 0, 0]
Mill Park
Mill Park
[200, 'Mill Park', 577000, 645000, 711000, 0, 0, 0]
Miners Rest
Miners Rest
[201, 'Miners Rest', 314500, 346250, 403500, 0, 0, 0]
Mitcham
Mitcham
[202, 'Mitcham', 890000, 1039000, 1205000, 580000, 695000, 835000]
Mitchell Park
Mitchell Park
[203, 'Mitchell Park', 0, 0, 0, 0, 0, 0]
Monbulk
Monbulk
[204, 'Monbulk', 0, 0, 0, 0, 0, 0]
Mont Albert North
Mont Albert North
[205, 'Mont Albert North', 1325000, 1660000, 2340000, 0, 0, 0]
Montmorency
Montmorency
[206, 'Montmorency', 730000, 858125, 1015000, 642000, 685000, 786500]
Montrose
Montrose
[207, 'Montrose', 672500, 750000, 850500, 0, 0, 0]
Moolap
Moolap
[208, 'Moolap', 0, 0, 0, 0, 0, 0]
Moonee Ponds
Moonee Ponds
[209, 'Moonee Ponds', 1080000, 1316250, 1850500, 325000, 412000, 1015500]
Moorabbin
Moorabbin
[210, 'Moorabbin', 930000, 1090500, 1321000, 0, 0, 0]
Mooroolbark
Mooroolbark
[211, 'Mooroolbark', 640000, 705000, 820000, 520000, 580000, 655000]
Mordialloc
Mordialloc
[212, 'Mordialloc', 0, 0, 0, 550000, 660000, 878000]
Mount Dandenong
Mount Dandenong
[213, 'Mount Dandenong', 0, 0, 0, 0, 0, 0]
Mount Eliza
Mount Eliza
[214, 'Mount Eliza', 977500, 1192500, 1467500, 0, 0, 0]
Mount Evelyn
Mount Evelyn
[215, 'Mount Evelyn', 592750, 610000, 675000, 0, 0, 0]
Mount Helen
Mount Helen
[216, 'Mount Helen', 365000, 470000, 579000, 0, 0, 0]
Mount Pleasant
Mount Pleasant
[217, 'Mount Pleasant', 255000, 319000, 335000, 0, 0, 0]
Mount Waverley
Mount Waverley
[218, 'Mount Waverley', 1301100, 1456000, 1644500, 733000, 950000, 1190000]
Mulgrave
Mulgrave
[219, 'Mulgrave', 880000, 922500, 1010000, 0, 0, 0]
Narre Warren North
Narre Warren North
[220, 'Narre Warren North', 0, 0, 0, 0, 0, 0]
Narre Warren South
Narre Warren South
[221, 'Narre Warren South', 525000, 630000, 731250, 0, 0, 0]
Narre Warren
Narre Warren
[222, 'Narre Warren', 560000, 605500, 662000, 0, 0, 0]
Newcomb
Newcomb
[223, 'Newcomb', 0, 0, 0, 0, 0, 0]
Newington
Newington
[224, 'Newington', 0, 0, 0, 0, 0, 0]
Newport
Newport
[225, 'Newport', 956000, 1200000, 1410000, 665000, 760000, 860000]
Noble Park North
Noble Park North
[226, 'Noble Park North', 620250, 657500, 718000, 0, 0, 0]
Norlane
Norlane
[227, 'Norlane', 255000, 269000, 296500, 0, 0, 0]
North Bendigo
North Bendigo
[228, 'North Bendigo', 0, 0, 0, 0, 0, 0]
North Melbourne
North Melbourne
[229, 'North Melbourne', 0, 0, 0, 498000, 567500, 799000]
North Shore
North Shore
[230, 'North Shore', 0, 0, 0, 0, 0, 0]
Northcote
Northcote
[231, 'Northcote', 1220000, 1325000, 1675000, 407500, 525000, 699000]
Notting Hill
Notting Hill
[232, 'Notting Hill', 0, 0, 0, 0, 0, 0]
Oakleigh East
Oakleigh East
[233, 'Oakleigh East', 1114000, 1210000, 1321000, 790000, 850500, 912000]
Oakleigh South
Oakleigh South
[234, 'Oakleigh South', 945000, 1085000, 1215000, 0, 0, 0]
Olinda
Olinda
[235, 'Olinda', 0, 0, 0, 0, 0, 0]
Ormond
Ormond
[236, 'Ormond', 1265000, 1486000, 1710000, 420000, 695000, 1100000]
Park Orchards
Park Orchards
[237, 'Park Orchards', 1421000, 1500000, 1800000, 0, 0, 0]
Parkdale
Parkdale
[238, 'Parkdale', 1200000, 1270000, 1485000, 650000, 793500, 930000]
Parkville
Parkville
[239, 'Parkville', 0, 0, 0, 0, 0, 0]
Pascoe Vale South
Pascoe Vale South
[240, 'Pascoe Vale South', 966000, 1125000, 1400000, 0, 0, 0]
Pascoe Vale
Pascoe Vale
[241, 'Pascoe Vale', 794000, 906000, 1198550, 496000, 600000, 725000]
Pearcedale
Pearcedale
[242, 'Pearcedale', 0, 0, 0, 0, 0, 0]
Plenty
Plenty
[243, 'Plenty', 0, 0, 0, 0, 0, 0]
Point Cook
Point Cook
[244, 'Point Cook', 541000, 600000, 705000, 0, 0, 0]
Port Melbourne
Port Melbourne
[245, 'Port Melbourne', 1335000, 1650000, 2100000, 545000, 710000, 1120000]
Preston
Preston
[246, 'Preston', 860000, 1010000, 1171000, 445150, 582500, 695500]
Princes Hill
Princes Hill
[247, 'Princes Hill', 0, 0, 0, 0, 0, 0]
Quarry Hill
Quarry Hill
[248, 'Quarry Hill', 0, 0, 0, 0, 0, 0]
Research
Research
[249, 'Research', 0, 0, 0, 0, 0, 0]
Reservoir
Reservoir
[250, 'Reservoir', 725000, 846000, 935000, 452000, 528750, 633000]
Richmond
Richmond
[251, 'Richmond', 1172000, 1277500, 1619000, 475500, 590000, 830000]
Ringwood
Ringwood
[252, 'Ringwood', 860000, 947500, 1110000, 511500, 598550, 736500]
Ripponlea
Ripponlea
[253, 'Ripponlea', 0, 0, 0, 0, 0, 0]
Rosanna
Rosanna
[254, 'Rosanna', 1160000, 1240000, 1380000, 0, 0, 0]
Rosebud
Rosebud
[255, 'Rosebud', 500000, 541500, 625000, 391500, 450150, 489000]
Rosebud West
Rosebud West
[256, 'Rosebud West', 0, 0, 0, 0, 0, 0]
Rowville
Rowville

In [285]:
print pricedf[pricedf['house_median_quartile']==0].count()
print pricedf[pricedf['unit_median_quartile']==0].count()

suburb_id                104
suburb                   104
house_low_quartile       104
house_median_quartile    104
house_high_quartile      104
unit_low_quartile        104
unit_median_quartile     104
unit_high_quartile       104
dtype: int64
suburb_id                217
suburb                   217
house_low_quartile       217
house_median_quartile    217
house_high_quartile      217
unit_low_quartile        217
unit_median_quartile     217
unit_high_quartile       217
dtype: int64

In [283]:
pricedf[pricedf['house_low_quartile']==0]

,suburb_id,suburb,house_low_quartile,house_median_quartile,house_high_quartile,unit_low_quartile,unit_median_quartile,unit_high_quartile
1,1,Aberfeldie,0,0,0,0,0,0
9,9,Ascot,0,0,0,0,0,0
15,15,Attwood,0,0,0,0,0,0
17,17,Avonsleigh,0,0,0,0,0,0
18,18,Bakery Hill,0,0,0,0,0,0
19,19,Balaclava,0,0,0,535000,576500,667000
24,24,Bangholme,0,0,0,0,0,0
29,29,Belgrave Heights,0,0,0,0,0,0
33,33,Bellfield,0,0,0,0,0,0
39,39,Bittern,0,0,0,0,0,0
44,44,Blairgowrie,0,0,0,0,0,0
49,49,Braybrook,0,0,0,471000,500000,580000
50,50,Briar Hill,0,0,0,0,0,0
59,59,Burnley,0,0,0,0,0,0
67,67,Carlton,0,0,0,320000,570000,926000
70,70,Carrum,0,0,0,450000,555000,620000
71,71,Caulfield East,0,0,0,0,0,0
73,73,Caulfield,0,0,0,570000,740000,1210000
78,78,Clematis,0,0,0,0,0,0
82,82,Coldstream,0,0,0,0,0,0
83,83,Collingwood,0,0,0,542000,740000,1162500
86,86,Cranbourne South,0,0,0,0,0,0
97,97,Devon Meadows,0,0,0,0,0,0
100,100,Docklands,0,0,0,480000,539000,815000
107,107,Drumcondra,0,0,0,0,0,0
109,109,Eaglemont,0,0,0,0,0,0
110,110,East Bendigo,0,0,0,0,0,0
112,112,East Melbourne,0,0,0,660000,810000,1350000
118,118,Epsom,0,0,0,0,0,0
119,119,Essendon North,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
243,243,Plenty,0,0,0,0,0,0
247,247,Princes Hill,0,0,0,0,0,0
248,248,Quarry Hill,0,0,0,0,0,0
249,249,Research,0,0,0,0,0,0
253,253,Ripponlea,0,0,0,0,0,0
256,256,Rosebud West,0,0,0,0,0,0
261,261,Sailors Gully,0,0,0,0,0,0
263,263,Sassafras,0,0,0,0,0,0
265,265,Seabrook,0,0,0,0,0,0
267,267,Seaholme,0,0,0,0,0,0
269,269,Selby,0,0,0,0,0,0
270,270,Sherbrooke,0,0,0,0,0,0
271,271,Skye,0,0,0,0,0,0
275,275,South Kingsville,0,0,0,0,0,0
277,277,Southbank,0,0,0,530000,612501,750000
279,279,Spring Gully,0,0,0,0,0,0
281,281,St Helena,0,0,0,0,0,0
285,285,Strathmore Heights,0,0,0,0,0,0
297,297,The Patch,0,0,0,0,0,0
299,299,Thomson,0,0,0,0,0,0
303,303,Travancore,0,0,0,360000,379000,535000
308,308,Wandana Heights,0,0,0,0,0,0
311,311,Warrandyte South,0,0,0,0,0,0
314,314,Waterways,0,0,0,0,0,0
315,315,Watsonia,0,0,0,0,0,0
316,316,Wattle Glen,0,0,0,0,0,0
319,319,West Bendigo,0,0,0,0,0,0
320,320,West Melbourne,0,0,0,465000,615000,792000
323,323,Whittington,0,0,0,0,0,0
324,324,Williamstown North,0,0,0,0,0,0

In [299]:
pricedf.loc[pricedf['house_low_quartile'] == 0, ['house_median_quartile']] = pricedf.house_median_quartile.mean()
pricedf.loc[pricedf['house_low_quartile'] == 0, ['unit_median_quartile']] = pricedf.unit_median_quartile.mean()

In [298]:
pricedf.unit_median_quartile.mean()

260292.9633027523

In [302]:
# pricedf['house_median_quartile'] = pricedf.house_median_quartile.astype(int)
pricedf['unit_median_quartile'] = pricedf.unit_median_quartile.astype(int)

/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [303]:
pricedf

,suburb_id,suburb,house_low_quartile,house_median_quartile,house_high_quartile,unit_low_quartile,unit_median_quartile,unit_high_quartile
0,0,Abbotsford,1165000.0,1271000,1490000,399000,557500,810000
1,1,Aberfeldie,0.0,649863,0,0,260292,0
2,2,Airport West,810000.0,888750,1035500,540000,680000,733750
3,3,Albanvale,514000.0,535000,572000,0,0,0
4,4,Albert Park,1605000.0,2120000,2905000,0,0,0
5,5,Alfredton,355000.0,440000,480000,0,0,0
6,6,Altona North,807000.0,855000,910000,592000,650000,723000
7,7,Ardeer,570000.0,630000,660000,0,0,0
8,8,Armadale,1705000.0,2247500,4100000,550000,725750,1200000
9,9,Ascot,0.0,649863,0,0,260292,0
10,10,Ascot Vale,1050000.0,1255000,1400000,440000,525000,880000
11,11,Ashburton,1702500.0,1850000,2129000,0,0,0
12,12,Ashwood,1212000.0,1335000,1495000,822000,890000,1320000
13,13,Aspendale Gardens,845000.0,911000,950000,0,0,0
14,14,Aspendale,1200000.0,1352500,1431000,0,0,0
15,15,Attwood,0.0,649863,0,0,260292,0
16,16,Avondale Heights,835000.0,900000,1000000,0,0,0
17,17,Avonsleigh,0.0,649863,0,0,260292,0
18,18,Bakery Hill,0.0,649863,0,0,260292,0
19,19,Balaclava,0.0,649863,0,535000,260292,667000
20,20,Ballarat Central,293250.0,382000,465000,0,0,0
21,21,Ballarat East,274500.0,315000,370000,0,0,0
22,22,Ballarat North,256000.0,339750,367500,0,0,0
23,23,Balwyn,1810000.0,2255500,2870000,720000,860000,1280000
24,24,Bangholme,0.0,649863,0,0,260292,0
25,25,Bayswater North,683000.0,730500,785000,440000,522500,617500
26,26,Bayswater,708000.0,800500,900000,435000,485000,600000
27,27,Beaconsfield,585000.0,692500,875000,0,0,0
28,28,Beaumaris,1445000.0,1690000,1842500,845000,1205000,1600000
29,29,Belgrave Heights,0.0,649863,0,0,260292,0
...,...,...,...,...,...,...,...,...
297,297,The Patch,0.0,649863,0,0,260292,0
298,298,Thomastown,605000.0,646000,700000,385000,440000,486000
299,299,Thomson,0.0,649863,0,0,260292,0
300,300,Thornbury,1115000.0,1250000,1440000,448500,725000,800000
301,301,Toorak,2150000.0,4750000,6250000,810000,1380000,2720000
302,302,Tootgarook,510000.0,551250,608000,0,0,0
303,303,Travancore,0.0,649863,0,360000,260292,535000
304,304,Truganina,430000.0,510000,590000,0,0,0
305,305,Upwey,600000.0,663000,745000,0,0,0
306,306,Vermont South,1125000.0,1225000,1301000,0,0,0
307,307,Viewbank,850000.0,940000,1061000,0,0,0
308,308,Wandana Heights,0.0,649863,0,0,260292,0
309,309,Wandin North,621000.0,660000,737518,0,0,0
310,310,Wantirna South,933000.0,1010000,1196000,0,0,0
311,311,Warrandyte South,0.0,649863,0,0,260292,0
312,312,Warrandyte,885000.0,1054000,1342000,0,0,0
313,313,Warranwood,826000.0,847000,945000,0,0,0
314,314,Waterways,0.0,649863,0,0,260292,0
315,315,Watsonia,0.0,649863,0,0,260292,0
316,316,Wattle Glen,0.0,649863,0,0,260292,0
317,317,Waurn Ponds,483000.0,558000,622000,0,0,0
318,318,Wendouree,227500.0,255500,289000,0,0,0
319,319,West Bendigo,0.0,649863,0,0,260292,0
320,320,West Melbourne,0.0,649863,0,465000,260292,792000
321,321,Westmeadows,500000.0,550000,610000,0,0,0
322,322,Wheelers Hill,999000.0,1130000,1272000,0,0,0
323,323,Whittington,0.0,649863,0,0,260292,0
324,324,Williamstown North,0.0,649863,0,0,260292,0
325,325,Wyndham Vale,410000.0,450000,505000,0,0,0
326,326,Yarraville,965000.0,1101000,1265500,470000,650000,780000

In [304]:
def human_format(num):
    magnitude = 0
    while abs(num) >= 1000:
        magnitude += 1
        num /= 1000.0
    # add more suffixes if you need them
    return '%.2f%s' % (num, ['', 'K', 'M', 'G', 'T', 'P'][magnitude])

print('the answer is %s' % human_format(7436313))

the answer is 7.44M

In [305]:
pricedf_temp = pricedf

In [306]:
pricedf_temp['house_median_quartile_string'] = pricedf_temp['house_median_quartile'].apply(human_format)
pricedf_temp['unit_median_quartile_string'] = pricedf_temp['unit_median_quartile'].apply(human_format)

/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Bharath/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [307]:
pricedf_temp

,suburb_id,suburb,house_low_quartile,house_median_quartile,house_high_quartile,unit_low_quartile,unit_median_quartile,unit_high_quartile,house_median_quartile_string,unit_median_quartile_string
0,0,Abbotsford,1165000.0,1271000,1490000,399000,557500,810000,1.27M,557.50K
1,1,Aberfeldie,0.0,649863,0,0,260292,0,649.86K,260.29K
2,2,Airport West,810000.0,888750,1035500,540000,680000,733750,888.75K,680.00K
3,3,Albanvale,514000.0,535000,572000,0,0,0,535.00K,0.00
4,4,Albert Park,1605000.0,2120000,2905000,0,0,0,2.12M,0.00
5,5,Alfredton,355000.0,440000,480000,0,0,0,440.00K,0.00
6,6,Altona North,807000.0,855000,910000,592000,650000,723000,855.00K,650.00K
7,7,Ardeer,570000.0,630000,660000,0,0,0,630.00K,0.00
8,8,Armadale,1705000.0,2247500,4100000,550000,725750,1200000,2.25M,725.75K
9,9,Ascot,0.0,649863,0,0,260292,0,649.86K,260.29K
10,10,Ascot Vale,1050000.0,1255000,1400000,440000,525000,880000,1.25M,525.00K
11,11,Ashburton,1702500.0,1850000,2129000,0,0,0,1.85M,0.00
12,12,Ashwood,1212000.0,1335000,1495000,822000,890000,1320000,1.33M,890.00K
13,13,Aspendale Gardens,845000.0,911000,950000,0,0,0,911.00K,0.00
14,14,Aspendale,1200000.0,1352500,1431000,0,0,0,1.35M,0.00
15,15,Attwood,0.0,649863,0,0,260292,0,649.86K,260.29K
16,16,Avondale Heights,835000.0,900000,1000000,0,0,0,900.00K,0.00
17,17,Avonsleigh,0.0,649863,0,0,260292,0,649.86K,260.29K
18,18,Bakery Hill,0.0,649863,0,0,260292,0,649.86K,260.29K
19,19,Balaclava,0.0,649863,0,535000,260292,667000,649.86K,260.29K
20,20,Ballarat Central,293250.0,382000,465000,0,0,0,382.00K,0.00
21,21,Ballarat East,274500.0,315000,370000,0,0,0,315.00K,0.00
22,22,Ballarat North,256000.0,339750,367500,0,0,0,339.75K,0.00
23,23,Balwyn,1810000.0,2255500,2870000,720000,860000,1280000,2.26M,860.00K
24,24,Bangholme,0.0,649863,0,0,260292,0,649.86K,260.29K
25,25,Bayswater North,683000.0,730500,785000,440000,522500,617500,730.50K,522.50K
26,26,Bayswater,708000.0,800500,900000,435000,485000,600000,800.50K,485.00K
27,27,Beaconsfield,585000.0,692500,875000,0,0,0,692.50K,0.00
28,28,Beaumaris,1445000.0,1690000,1842500,845000,1205000,1600000,1.69M,1.21M
29,29,Belgrave Heights,0.0,649863,0,0,260292,0,649.86K,260.29K
...,...,...,...,...,...,...,...,...,...,...
297,297,The Patch,0.0,649863,0,0,260292,0,649.86K,260.29K
298,298,Thomastown,605000.0,646000,700000,385000,440000,486000,646.00K,440.00K
299,299,Thomson,0.0,649863,0,0,260292,0,649.86K,260.29K
300,300,Thornbury,1115000.0,1250000,1440000,448500,725000,800000,1.25M,725.00K
301,301,Toorak,2150000.0,4750000,6250000,810000,1380000,2720000,4.75M,1.38M
302,302,Tootgarook,510000.0,551250,608000,0,0,0,551.25K,0.00
303,303,Travancore,0.0,649863,0,360000,260292,535000,649.86K,260.29K
304,304,Truganina,430000.0,510000,590000,0,0,0,510.00K,0.00
305,305,Upwey,600000.0,663000,745000,0,0,0,663.00K,0.00
306,306,Vermont South,1125000.0,1225000,1301000,0,0,0,1.23M,0.00
307,307,Viewbank,850000.0,940000,1061000,0,0,0,940.00K,0.00
308,308,Wandana Heights,0.0,649863,0,0,260292,0,649.86K,260.29K
309,309,Wandin North,621000.0,660000,737518,0,0,0,660.00K,0.00
310,310,Wantirna South,933000.0,1010000,1196000,0,0,0,1.01M,0.00
311,311,Warrandyte South,0.0,649863,0,0,260292,0,649.86K,260.29K
312,312,Warrandyte,885000.0,1054000,1342000,0,0,0,1.05M,0.00
313,313,Warranwood,826000.0,847000,945000,0,0,0,847.00K,0.00
314,314,Waterways,0.0,649863,0,0,260292,0,649.86K,260.29K
315,315,Watsonia,0.0,649863,0,0,260292,0,649.86K,260.29K
316,316,Wattle Glen,0.0,649863,0,0,260292,0,649.86K,260.29K
317,317,Waurn Ponds,483000.0,558000,622000,0,0,0,558.00K,0.00
318,318,Wendouree,227500.0,255500,289000,0,0,0,255.50K,0.00
319,319,West Bendigo,0.0,649863,0,0,260292,0,649.86K,260.29K
320,320,West Melbourne,0.0,649863,0,465000,260292,792000,649.86K,260.29K
321,321,Westmeadows,500000.0,550000,610000,0,0,0,550.00K,0.00
322,322,Wheelers Hill,999000.0,1130000,1272000,0,0,0,1.13M,0.00
323,323,Whittington,0.0,649863,0,0,260292,0,649.86K,260.29K
324,324,Williamstown North,0.0,649863,0,0,260292,0,649.86K,260.29K
325,325,Wyndham Vale,410000.0,450000,505000,0,0,0,450.00K,0.00
326,326,Yarraville,965000.0,1101000,1265500,470000,650000,780000,1.10M,650.00K

### Write to CSV

In [309]:
pricedf_temp.to_csv('houseprice_v6.csv', sep=',')